test_app/config/routes.rb
Rails.application.routes.draw do
  resources :drinks

root 'drinks#index'

end

test_app/app/models/drink.rb
class Drink < ActiveRecord::Base
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

test_app/app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:name, :temperature)
    end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/drinks_helper.rb
module DrinksHelper
end

test_app/app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.number_field :temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

test_app/app/views/drinks/edit.html.erb
<h1>Editing Drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

test_app/app/views/drinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drinks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinks.each do |drink| %>
      <tr>
        <td><%= drink.name %></td>
        <td><%= drink.temperature %></td>
        <td><%= link_to 'Show', drink %></td>
        <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
        <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drink', new_drink_path %>

test_app/app/views/drinks/new.html.erb
<h1>New Drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

test_app/app/views/drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @drink.name %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @drink.temperature %>
</p>

<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>